### ISSUE TITLE
LMDeploy Support

### ISSUE THREAD

**Issue by corupta** [corupta/jetson-containers-jp5#1]
### Search before asking

- [x] I have searched the jetson-containers [issues](https://github.com/dusty-nv/jetson-containers/issues) and found no similar feature requests.

### Description

Implemented `lmdeploy` `0.8.0` support
* Build with `CUDA_VERSION=12.2 PYTHON_VERSION=3.12 PYTORCH_VERSION=2.7 NUMPY_VERSION=1 CUDNN_VERSION=9.10 jetson-containers build lmdeploy:0.8.1` or pull from docker hub.
```
services:
  llm-server:
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    ports:
      - 9000:9000
    environment:
      - DOCKER_PULL=always
      - HUGGING_FACE_HUB_TOKEN=${HUGGINGFACE_TOKEN}
      - HF_HUB_CACHE=/root/.cache/huggingface
    pull_policy: always
    volumes:
      - /mnt/nvme/cache:/root/.cache
    image: corupta/lmdeploy:0.8.1-r35.6.1-cp312-cu122-20.04
    command: lmdeploy serve api_server Intel/DeepSeek-R1-0528-Qwen3-8B-int4-AutoRound-awq-inc
      --reasoning-parser deepseek-r1
      --backend turbomind
      --cache-max-entry-count 0.5
      --quant-policy 8
      --model-format awq
      --server-port 9000
```

https://github.com/user-attachments/assets/e2515eda-365a-4d66-a54f-bc0b5aee1a64

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!
